/**
 * Image generation service — runs server-side.
 *
 * Two models:
 * - Imagen 4 (`imagen-4.0-generate-001`) — text-only, used for style exploration
 * - Gemini 3 Pro Image Preview (`gemini-3-pro-image-preview`) — multimodal, used for
 *   character looks, environment looks, and shot frames (accepts reference images)
 */
import { GoogleGenAI } from '@google/genai';
import { saveBase64, readAsBase64 } from '../storage.js';

const getAI = () => new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! });

// ─── Multimodal Image Generation (gemini-3-pro-image-preview) ───────

type ContentPart = { text: string } | { inlineData: { mimeType: string; data: string } };

/**
 * Generate an image using gemini-3-pro-image-preview with reference images.
 * Accepts an array of text + image parts as input.
 * Returns the storage path of the generated image.
 */
export const generateImageWithRefs = async (
  parts: ContentPart[],
  aspectRatio = '16:9'
): Promise<string> => {
  const ai = getAI();

  const response = await ai.models.generateContent({
    model: 'gemini-3-pro-image-preview',
    contents: [{ role: 'user', parts }],
    config: {
      responseModalities: ['IMAGE'],
      // @ts-ignore — imageConfig not in all SDK type versions
      imageConfig: { aspectRatio }
    }
  });

  // Extract image from response
  const candidate = response.candidates?.[0];
  if (!candidate?.content?.parts) throw new Error('No image generated by gemini-3-pro-image-preview');

  for (const part of candidate.content.parts) {
    if ((part as any).inlineData) {
      const { data, mimeType } = (part as any).inlineData;
      const ext = mimeType?.includes('png') ? 'png' : 'png';
      return saveBase64(data, 'images', ext);
    }
  }

  throw new Error('No image data in gemini-3-pro-image-preview response');
};

/**
 * Helper: read a storage path and return an inlineData part.
 */
export const imagePartFromPath = (storagePath: string): ContentPart => ({
  inlineData: {
    mimeType: 'image/png',
    data: readAsBase64(storagePath),
  }
});

// ─── Style Grid Generation (Imagen 4, text-only) ────────────────────

/**
 * Generate style options. Either from user notes or from a default set.
 * Returns 4 images with distinct visual directions.
 * Stays on Imagen 4 — style exploration doesn't need reference images.
 */
export const generateStyleOptions = async (
  deity: string,
  styleNotes?: string,
  projectId?: string
): Promise<{ style: string; assetPath: string }[]> => {
  const ai = getAI();

  const directions = styleNotes
    ? [
        `${styleNotes}`,
        `${styleNotes}, with dramatic chiaroscuro shadows and Renaissance-inspired composition`,
        `${styleNotes}, reimagined with high-key ethereal golden lighting and divine bloom effects`,
        `${styleNotes}, as vintage 16mm film with warm analog grain and nostalgic color grading`,
      ]
    : [
        `Hyperrealistic cinematic portrait of ${deity}, 35mm Kodak film look, natural light`,
        `${deity} in dramatic Caravaggio-style chiaroscuro, deep shadows, single light source, oil painting realism`,
        `${deity} in ethereal divine light, high-key photography, golden bloom, heavenly atmosphere, lens flare`,
        `${deity} as vintage 16mm film still, warm analog grain, faded colors, nostalgic Indian cinema aesthetic`,
      ];

  const results: { style: string; assetPath: string }[] = [];

  const settled = await Promise.allSettled(
    directions.map(async (direction) => {
      const prompt = `Cinematic film still. ${direction}. Focus on lighting, atmosphere, and visual style. High production value, no text, no watermark.`;
      const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt,
        config: {
          numberOfImages: 1,
          aspectRatio: '16:9',
        }
      });

      const imageData = response.generatedImages?.[0]?.image?.imageBytes;
      if (!imageData) throw new Error('No image generated');

      const assetPath = saveBase64(imageData, 'images', 'png');
      return { style: direction, assetPath };
    })
  );

  for (const result of settled) {
    if (result.status === 'fulfilled') {
      results.push(result.value);
    } else {
      console.error('[imagen] Style generation failed:', result.reason);
    }
  }

  return results;
};

// ─── Single Style Image Generation (Imagen 4) ──────────────────────

/**
 * Generate a single style image from a complete style direction prompt.
 * Used by the brainstorm→visualize flow. Stays on Imagen 4.
 */
export const generateSingleStyleImage = async (
  styleDescription: string,
  subject: string
): Promise<string> => {
  const ai = getAI();
  const prompt = `Cinematic film still showcasing a specific visual style. ${styleDescription}. The scene evokes the world of ${subject}. Focus entirely on lighting, atmosphere, color, and visual style. High production value, no text, no watermark.`;

  const response = await ai.models.generateImages({
    model: 'imagen-4.0-generate-001',
    prompt,
    config: {
      numberOfImages: 1,
      aspectRatio: '16:9',
    }
  });

  const imageData = response.generatedImages?.[0]?.image?.imageBytes;
  if (!imageData) throw new Error('No image generated');

  return saveBase64(imageData, 'images', 'png');
};

// ─── Character Look Generation (gemini-3-pro-image-preview) ─────────

/**
 * Generate 3 character look variations using gemini-3-pro-image-preview.
 * Uses the locked style image as a visual reference.
 */
export const generateCharacterLooks = async (
  character: { name: string; description: string },
  styleDNA: string,
  styleImagePath?: string,
  userFeedback?: string
): Promise<string[]> => {
  const compositions = [
    'Close-up portrait, looking at camera, detailed face and ornaments',
    'Mid-shot action pose, dynamic composition, full upper body visible',
    'Full body shot, detailed costume and environment, wide framing'
  ];

  const settled = await Promise.allSettled(
    compositions.map(async (composition) => {
      const parts: ContentPart[] = [];

      // Style reference image
      if (styleImagePath) {
        parts.push({ text: 'Generate a character portrait in this visual style:' });
        parts.push(imagePartFromPath(styleImagePath));
      }

      parts.push({ text: `Style: ${styleDNA}` });
      parts.push({ text: `Character: ${character.name} — ${character.description}` });
      parts.push({ text: `Composition: ${composition}` });
      parts.push({ text: 'Cinematic lighting, high detail, film quality. No text, no watermark.' });

      if (userFeedback) {
        parts.push({ text: `FEEDBACK: ${userFeedback}` });
      }

      return generateImageWithRefs(parts);
    })
  );

  const paths: string[] = [];
  for (const result of settled) {
    if (result.status === 'fulfilled') {
      paths.push(result.value);
    } else {
      console.error('[imagen] Character look failed:', result.reason);
    }
  }
  return paths;
};

// ─── Environment Look Generation (gemini-3-pro-image-preview) ───────

/**
 * Generate 3 environment look variations using gemini-3-pro-image-preview.
 * Uses the locked style image as a visual reference.
 */
export const generateEnvironmentLooks = async (
  environment: { name: string; description: string },
  styleDNA: string,
  styleImagePath?: string
): Promise<string[]> => {
  const framings = [
    'Wide establishing shot, full environment visible',
    'Medium shot showing key environmental details and atmosphere',
    'Cinematic low-angle view emphasizing scale and grandeur'
  ];

  const settled = await Promise.allSettled(
    framings.map(async (framing) => {
      const parts: ContentPart[] = [];

      if (styleImagePath) {
        parts.push({ text: 'Generate an environment scene in this visual style:' });
        parts.push(imagePartFromPath(styleImagePath));
      }

      parts.push({ text: `Style: ${styleDNA}` });
      parts.push({ text: `Environment: ${environment.name} — ${environment.description}` });
      parts.push({ text: `Framing: ${framing}` });
      parts.push({ text: 'No characters, focus on environment and atmosphere. Cinematic lighting, high detail. No text, no watermark.' });

      return generateImageWithRefs(parts);
    })
  );

  const paths: string[] = [];
  for (const result of settled) {
    if (result.status === 'fulfilled') {
      paths.push(result.value);
    } else {
      console.error('[imagen] Environment look failed:', result.reason);
    }
  }
  return paths;
};

// ─── Shot Start Frame Generation (gemini-3-pro-image-preview) ───────

/**
 * Generate a shot's start frame with full reference chain.
 *
 * Uses a numbered reference index approach — each image is labeled with its role,
 * explicit usage instructions tell the model what to extract from each, and a
 * priority order resolves conflicts between references.
 */
export const generateShotStartFrame = async (opts: {
  visualPrompt: string;
  styleDNA: string;
  styleImagePath?: string;
  characterRefs: { name: string; imagePath: string }[];
  environmentRef?: { name: string; imagePath: string };
  prevShotEndFramePath?: string;
  userFeedback?: string;
}): Promise<string> => {
  const parts: ContentPart[] = [];

  // ── Build reference index ──
  // Number each image so the model can unambiguously refer to them.
  let imageIdx = 0;
  const charImageLabels: string[] = [];

  // Character references (highest priority — identity must be preserved)
  for (const ref of opts.characterRefs) {
    imageIdx++;
    parts.push({ text: `Image ${imageIdx} = Character reference: ${ref.name}` });
    parts.push(imagePartFromPath(ref.imagePath));
    charImageLabels.push(`Image ${imageIdx} (${ref.name})`);
  }

  // Style reference
  if (opts.styleImagePath) {
    imageIdx++;
    parts.push({ text: `Image ${imageIdx} = Style reference` });
    parts.push(imagePartFromPath(opts.styleImagePath));
  }

  // Environment reference
  if (opts.environmentRef) {
    imageIdx++;
    parts.push({ text: `Image ${imageIdx} = Environment reference: ${opts.environmentRef.name}` });
    parts.push(imagePartFromPath(opts.environmentRef.imagePath));
  }

  // Continuity reference (previous shot's end frame)
  if (opts.prevShotEndFramePath) {
    imageIdx++;
    parts.push({ text: `Image ${imageIdx} = Last-scene continuity reference` });
    parts.push(imagePartFromPath(opts.prevShotEndFramePath));
  }

  // ── Reference usage instructions ──
  const usageLines: string[] = [];

  if (charImageLabels.length > 0) {
    usageLines.push(`- Character references (${charImageLabels.join(', ')}): preserve identity, face, hairstyle, silhouette, body proportions, and signature wardrobe details. Do not redesign the character.`);
  }
  if (opts.styleImagePath) {
    usageLines.push('- Style reference: transfer only artistic treatment, lighting logic, palette, texture, lens language, and finish. Do not borrow subject identity from the style reference.');
  }
  if (opts.environmentRef) {
    usageLines.push('- Environment reference: transfer location design, materials, weather, ambience, and spatial cues. Do not change the setting unless required by the scene description.');
  }
  if (opts.prevShotEndFramePath) {
    usageLines.push('- Continuity reference: continue the action, framing logic, emotional beat, and object continuity from the previous shot. The image should feel like a natural continuation.');
  }

  if (usageLines.length > 0) {
    parts.push({ text: `REFERENCE USAGE\n${usageLines.join('\n')}` });
  }

  // ── Scene description ──
  parts.push({ text: `SCENE DESCRIPTION\n${opts.visualPrompt}` });
  parts.push({ text: `Style DNA: ${opts.styleDNA}` });

  if (opts.userFeedback) {
    parts.push({ text: `DIRECTOR FEEDBACK: ${opts.userFeedback}` });
  }

  // ── Output requirements + priority ──
  const outputReqs: string[] = [
    'Generate a single cinematic frame for this scene.'
  ];
  if (opts.prevShotEndFramePath) outputReqs.push('The image must feel like a natural continuation of the continuity reference.');
  if (charImageLabels.length > 0) outputReqs.push('The subject must remain clearly the same character as the character reference(s).');
  if (opts.environmentRef) outputReqs.push('The environment should clearly evoke the environment reference.');
  if (opts.styleImagePath) outputReqs.push('The render should use the visual language of the style reference.');

  parts.push({ text: outputReqs.join('\n') });

  parts.push({ text: `PRIORITY ORDER\n1. Character identity\n2. Temporal continuity with the last scene\n3. Environment fidelity\n4. Style fidelity` });

  parts.push({ text: 'NEGATIVE CONSTRAINTS\n- Do not borrow subject identity from the style reference.\n- Do not redesign the character.\n- Do not change the setting unless required by the scene description.\n- Do not break continuity in costume, pose progression, or major props.\n- No text, no watermark, no logos.' });

  return generateImageWithRefs(parts);
};

// ─── Shot End Frame Generation (gemini-3-pro-image-preview) ──────────

/**
 * Generate a shot's end frame from its start frame + motion prompt.
 * The start frame IS the continuity reference — the end frame shows
 * where the camera/action ends up after the described motion.
 */
export const generateShotEndFrame = async (opts: {
  startFramePath: string;
  motionPrompt: string;
  styleImagePath?: string;
  styleDNA: string;
}): Promise<string> => {
  const parts: ContentPart[] = [];

  // Image 1 = start frame (primary reference)
  parts.push({ text: 'Image 1 = Start frame of this shot (continuity + character + environment reference)' });
  parts.push(imagePartFromPath(opts.startFramePath));

  // Image 2 = style reference (optional)
  if (opts.styleImagePath) {
    parts.push({ text: 'Image 2 = Style reference' });
    parts.push(imagePartFromPath(opts.styleImagePath));
  }

  parts.push({ text: `REFERENCE USAGE
- Image 1 (start frame): This is the beginning of the shot. Preserve character identity, costume, environment, props, and spatial layout exactly. The end frame is the SAME scene moments later.
- ${opts.styleImagePath ? 'Image 2 (style): maintain the same artistic treatment, lighting, palette, and finish.' : `Style DNA: ${opts.styleDNA}`}` });

  parts.push({ text: `MOTION DESCRIPTION\n${opts.motionPrompt}` });

  parts.push({ text: `Generate the END FRAME of this shot — what the camera sees AFTER the motion described above has occurred.

OUTPUT REQUIREMENTS
- Same scene, same characters, same environment as Image 1.
- Camera and/or characters have moved according to the motion description.
- Maintain exact character identity, costume, and props.
- Maintain style consistency.
- No text, no watermark, no logos.

PRIORITY ORDER
1. Character identity continuity with Image 1
2. Environment continuity with Image 1
3. Motion fidelity (show the result of the described movement)
4. Style fidelity` });

  return generateImageWithRefs(parts);
};
