/**
 * Image generation service — runs server-side.
 *
 * Two models:
 * - Imagen 4 (`imagen-4.0-generate-001`) — text-only, used for style exploration
 * - Gemini 3 Pro Image Preview (`gemini-3-pro-image-preview`) — multimodal, used for
 *   character looks, environment looks, and shot frames (accepts reference images)
 */
import { GoogleGenAI } from '@google/genai';
import { saveBase64, readAsBase64 } from '../storage.js';

const getAI = () => new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! });

/** Detect actual image format from base64 data */
const detectImageExt = (base64: string): string => {
  if (base64.startsWith('/9j/') || base64.startsWith('/9j+')) return 'jpg';
  return 'png';
};

// ─── Multimodal Image Generation (gemini-3-pro-image-preview) ───────

export type ContentPart = { text: string } | { inlineData: { mimeType: string; data: string } };

/**
 * Generate an image using gemini-3-pro-image-preview with reference images.
 * Accepts an array of text + image parts as input.
 * Returns the storage path of the generated image.
 */
// Fallback chain used when no explicit model is passed in. Pro is primary,
// Flash is the 503/429 fallback. When the caller passes an explicit `model`
// (from the project's image_model / storyboard_provider spec's runtimeModel
// field), only that single model is attempted — no Pro→Flash fallback,
// because the artist's pick is the contract.
const DEFAULT_IMAGE_MODELS = ['gemini-3-pro-image-preview', 'gemini-3.1-flash-image-preview'] as const;

export const generateImageWithRefs = async (
  parts: ContentPart[],
  aspectRatio = '16:9',
  /** Override model from the registry spec. When set, only this model runs. */
  model?: string,
): Promise<string> => {
  const ai = getAI();
  let lastError: Error | null = null;
  const models = model ? [model] : DEFAULT_IMAGE_MODELS;

  for (const candidate of models) {
    try {
      const response = await ai.models.generateContent({
        model: candidate,
        contents: [{ role: 'user', parts }],
        config: {
          responseModalities: ['IMAGE'],
          // @ts-ignore — imageConfig not in all SDK type versions
          imageConfig: { aspectRatio }
        }
      });

      const images = await extractImages(response);
      if (images.length === 0) throw new Error(`No image generated by ${candidate}`);
      if (!model && candidate !== DEFAULT_IMAGE_MODELS[0]) console.log(`[imagen] Fallback to ${candidate} succeeded`);
      return images[0];
    } catch (err: any) {
      lastError = err;
      const status = err?.status || err?.code || '';
      const msg = err?.message || '';
      // Retry on 503/429/overloaded — don't retry on 400 (bad prompt) or auth errors
      if (String(status) === '503' || String(status) === '429' || msg.includes('UNAVAILABLE') || msg.includes('overloaded') || msg.includes('high demand')) {
        if (model) {
          // Explicit-model mode: no Pro→Flash fallback. Propagate the overload.
          throw err;
        }
        console.warn(`[imagen] ${candidate} unavailable (${status}), trying fallback...`);
        continue;
      }
      throw err; // Non-retryable error — propagate immediately
    }
  }

  throw lastError || new Error('All image models failed');
};

/**
 * Extract all generated images from a Gemini response.
 * Returns array of saved storage paths.
 */
const extractImages = async (response: any): Promise<string[]> => {
  const candidate = response.candidates?.[0];
  if (!candidate?.content?.parts) return [];

  const paths: string[] = [];
  for (const part of candidate.content.parts) {
    if ((part as any).inlineData) {
      const { data } = (part as any).inlineData;
      paths.push(await saveBase64(data, 'images', detectImageExt(data)));
    }
  }
  return paths;
};

/**
 * Helper: read a storage path and return an inlineData part.
 */
export const imagePartFromPath = async (storagePath: string): Promise<ContentPart> => ({
  inlineData: {
    mimeType: 'image/png',
    data: await readAsBase64(storagePath),
  }
});

// ─── Style Grid Generation (Imagen 4, text-only) ────────────────────

/**
 * Generate style options. Either from user notes or from a default set.
 * Returns 4 images with distinct visual directions.
 * Stays on Imagen 4 — style exploration doesn't need reference images.
 */
export const generateStyleOptions = async (
  deity: string,
  styleNotes?: string,
  projectId?: string
): Promise<{ style: string; assetPath: string }[]> => {
  const ai = getAI();

  const directions = styleNotes
    ? [
        `${styleNotes}`,
        `${styleNotes}, with dramatic chiaroscuro shadows and Renaissance-inspired composition`,
        `${styleNotes}, reimagined with high-key ethereal golden lighting and divine bloom effects`,
        `${styleNotes}, as vintage 16mm film with warm analog grain and nostalgic color grading`,
      ]
    : [
        // Default seeds are deliberately medium-neutral. The artist's locked
        // style preset (or uploaded reference) is the visual ground truth;
        // hard-coding "hyperrealistic" / "film still" here was leaking realism
        // into stylized projects. See docs/cinematic-leak-audit-2026-05-12.md.
        `Reference frame for ${deity}, devotional Indian visual treatment, natural light, balanced composition`,
        `${deity} rendered with dramatic chiaroscuro shadows and a single warm light source, deep grounded mood`,
        `${deity} in ethereal divine light with a high-key palette, soft bloom, devotional atmosphere`,
        `${deity} with warm earthy color and tactile material texture, nostalgic Indian devotional treatment`,
      ];

  const results: { style: string; assetPath: string }[] = [];

  const settled = await Promise.allSettled(
    directions.map(async (direction) => {
      const prompt = `${direction}. Focus on lighting, atmosphere, and visual treatment. High production value, no text, no watermark.`;
      const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt,
        config: {
          numberOfImages: 1,
          aspectRatio: '16:9',
        }
      });

      const imageData = response.generatedImages?.[0]?.image?.imageBytes;
      if (!imageData) throw new Error('No image generated');

      const assetPath = await saveBase64(imageData, 'images', detectImageExt(imageData));
      return { style: direction, assetPath };
    })
  );

  for (const result of settled) {
    if (result.status === 'fulfilled') {
      results.push(result.value);
    } else {
      console.error('[imagen] Style generation failed:', result.reason);
    }
  }

  return results;
};

// ─── Single Style Image Generation (gemini-3-pro-image-preview) ─────

/**
 * Generate a single style image from a complete style direction prompt.
 * Used by the brainstorm→visualize flow.
 */
/**
 * Build the default style visualization prompt from description + subject.
 * Produces a reusable style reference frame — not a scene, character portrait, or poster.
 */
export const buildStylePrompt = (styleDescription: string, subject: string): string => {
  return `Create one reusable visual style reference frame for an Indian devotional music video about ${subject}. ${styleDescription}

The image should demonstrate the style system clearly: lighting behavior, color palette, texture or medium, rendering approach, and atmosphere. Use a devotional visual motif or environment detail, but keep the focus on style rather than story.

It may be photographic, painterly, illustrated, miniature-inspired, or mixed-media if the style direction calls for it. High production value, no text, no watermark.

Do not make a character portrait, storyboard frame, poster, collage, or narrative scene. Keep the composition clean enough that the visual treatment is easy to read and reuse downstream.

Avoid: generic AI fantasy, muddy over-detailing, random divine VFX, incoherent cultural references.`;
};

export const generateSingleStyleImage = async (
  styleDescription: string,
  subject: string,
  /** If set, this is the exact prompt to send (artist-edited). */
  generationPrompt?: string,
): Promise<string> => {
  const prompt = generationPrompt || buildStylePrompt(styleDescription, subject);
  const parts: ContentPart[] = [{ text: prompt }];
  return generateImageWithRefs(parts);
};

// ─── Character Look Generation (gemini-3-pro-image-preview) ─────────

/**
 * Generate 3 character look variations via 3 parallel API calls with the SAME prompt.
 * gemini-3-pro-image-preview returns only 1 image per response and doesn't support
 * candidateCount, so parallel calls are the only real-time path. Same prompt →
 * natural variation from model sampling — user picks the best.
 */
/**
 * Build the default character generation prompt from description + style.
 * This is the template that gets saved to `generation_prompt` on first gen.
 * The artist can then edit it directly or refine via LLM.
 */
export const buildCharacterPrompt = (
  character: { name: string; description: string },
  opts?: { styleIdx?: number; userRefIdx?: number }
): string => {
  // Medium-neutral prompt: the locked style image (Image styleIdx) is the
  // ground truth for medium and rendering approach. Hard-coding "cinematic"
  // / "natural cinematic lighting" / "real film still" here was leaking
  // realism into stylized projects (miniature, painterly, illustrated). See
  // docs/cinematic-leak-audit-2026-05-12.md.
  let prompt = opts?.styleIdx
    ? `Generate ONE character reference portrait. Match the visual style EXACTLY from Image ${opts.styleIdx} — same lighting, color palette, texture, and rendering approach.`
    : `Generate ONE character reference portrait.`;
  prompt += `\n\n${character.name} — ${character.description}`;
  if (opts?.userRefIdx) {
    prompt += `\n\nImage ${opts.userRefIdx} is a reference the director provided for this character — match its identity (face, costume, silhouette, key iconography). The style image (Image ${opts.styleIdx || 1}) is the source of truth for HOW to render them.`;
  }
  prompt += `\n\nThis is a REUSABLE CHARACTER REFERENCE — it will be used across many different shots and scenes.
- Mid-shot portrait: upper body and face clearly visible
- NEUTRAL POSE: hands relaxed at sides or in a natural resting position
- Do NOT show the character holding anything, performing any action, or interacting with objects
- Do NOT include props, weapons, lamps, offerings, or ritual items in hand
- Focus on: face, skin, expression, costume, ornaments, jewelry, crown/headpiece, hair
- Plain or softly blurred background — the character should be isolated for reuse
- Eye-level framing; lighting follows the style image`;
  prompt += `\n\nOne single image. No collage, no grid, no multiple panels. No text, no watermark.
Avoid: overly AI/CGI look, excessive intricate detail, generic fantasy.`;
  return prompt;
};

export const generateCharacterLooks = async (
  character: { name: string; description: string },
  styleImagePath?: string,
  userFeedback?: string,
  aspectRatio: string = '16:9',
  userRefImagePath?: string,
  /** If set, this is the exact prompt to send (artist-edited or LLM-refined). */
  generationPrompt?: string,
  /** Model name from the registry spec. Defaults to Nano Banana Pro. */
  model: string = 'gemini-3-pro-image-preview',
): Promise<string[]> => {
  const ai = getAI();
  const N = 3;

  const parts: ContentPart[] = [];
  const imageLabels: string[] = [];
  if (styleImagePath) {
    imageLabels.push('Style reference');
    parts.push({ text: `Image ${imageLabels.length} = Style reference` });
    parts.push(await imagePartFromPath(styleImagePath));
  }
  if (userRefImagePath) {
    imageLabels.push('User-supplied character reference');
    parts.push({ text: `Image ${imageLabels.length} = User-supplied character reference` });
    parts.push(await imagePartFromPath(userRefImagePath));
  }

  const styleIdx = styleImagePath ? 1 : undefined;
  const userRefIdx = userRefImagePath ? (styleImagePath ? 2 : 1) : undefined;

  // Use the saved generation_prompt if provided, otherwise build from template
  let prompt: string;
  if (generationPrompt) {
    prompt = generationPrompt;
    if (userFeedback) prompt += `\n\nDirector note: ${userFeedback}`;
  } else {
    prompt = buildCharacterPrompt(character, { styleIdx, userRefIdx });
    if (userFeedback) prompt += `\n\nDirector note: ${userFeedback}`;
  }

  parts.push({ text: prompt });

  const singleCall = async (modelName: string): Promise<string | null> => {
    try {
      const response = await ai.models.generateContent({
        model: modelName,
        contents: [{ role: 'user', parts }],
        config: {
          responseModalities: ['IMAGE'],
          // @ts-ignore
          imageConfig: { aspectRatio }
        }
      });
      const paths = await extractImages(response);
      return paths[0] || null;
    } catch (err) {
      console.error(`[imagen] Character variant failed (${modelName}):`, err);
      return null;
    }
  };

  let activeModel = model;
  let results = await Promise.all(Array.from({ length: N }, () => singleCall(activeModel)));
  let paths = results.filter((p): p is string => p !== null);
  if (paths.length === 0) {
    const fallback = DEFAULT_IMAGE_MODELS.find((candidate) => candidate !== activeModel);
    if (fallback) {
      console.warn(`[imagen] Character looks (${activeModel}) returned 0/${N}; retrying with ${fallback}`);
      activeModel = fallback;
      results = await Promise.all(Array.from({ length: N }, () => singleCall(activeModel)));
      paths = results.filter((p): p is string => p !== null);
    }
  }
  console.log(`[imagen] Character looks (${activeModel}): got ${paths.length}/${N} images via parallel calls`);
  if (paths.length === 0) {
    throw new Error(`Image provider returned zero character look images after ${N} attempts.`);
  }
  return paths;
};

// ─── Environment Look Generation (gemini-3-pro-image-preview) ───────

/**
 * Generate 3 environment look variations via 3 parallel API calls with the SAME prompt.
 * Natural sampling variation → user picks the best.
 */
/**
 * Build the default environment generation prompt from description + style.
 * Saved to `generation_prompt` on first gen, then editable by the artist.
 */
export const buildEnvironmentPrompt = (
  environment: { name: string; description: string },
  opts?: { styleIdx?: number; userRefIdx?: number }
): string => {
  // Medium-neutral. Style image is the visual ground truth — don't fight it
  // in text. See docs/cinematic-leak-audit-2026-05-12.md.
  let prompt = opts?.styleIdx
    ? `Generate ONE environment shot. Match the visual style EXACTLY from Image ${opts.styleIdx} — same lighting, color palette, texture, and rendering approach. No characters or figures.`
    : `Generate ONE environment shot. No characters or figures.`;
  prompt += `\n\n${environment.name} — ${environment.description}`;
  if (opts?.userRefIdx) {
    prompt += `\n\nImage ${opts.userRefIdx} is a reference the director provided for this environment — match its geography, architecture, and mood. The style image (Image ${opts.styleIdx || 1}) is the source of truth for HOW it's rendered.`;
  }
  prompt += `\n\nWide establishing shot, full environment visible, empty scene.`;
  prompt += `\n\nOne single image. No collage, no grid, no multiple panels. No text, no watermark.
Avoid: overly AI/CGI look, excessive intricate detail, generic fantasy.`;
  return prompt;
};

export const generateEnvironmentLooks = async (
  environment: { name: string; description: string },
  styleImagePath?: string,
  aspectRatio: string = '16:9',
  userRefImagePath?: string,
  userNote?: string,
  /** If set, this is the exact prompt to send (artist-edited or LLM-refined). */
  generationPrompt?: string,
  /** Model name from the registry spec. Defaults to Nano Banana Pro. */
  model: string = 'gemini-3-pro-image-preview',
): Promise<string[]> => {
  const ai = getAI();
  const N = 3;

  const parts: ContentPart[] = [];
  if (styleImagePath) {
    parts.push({ text: 'Image 1 = Style reference' });
    parts.push(await imagePartFromPath(styleImagePath));
  }
  if (userRefImagePath) {
    const idx = styleImagePath ? 2 : 1;
    parts.push({ text: `Image ${idx} = User-supplied environment reference` });
    parts.push(await imagePartFromPath(userRefImagePath));
  }

  const styleIdx = styleImagePath ? 1 : undefined;
  const userRefIdx = userRefImagePath ? (styleImagePath ? 2 : 1) : undefined;

  // Use the saved generation_prompt if provided, otherwise build from template
  let prompt: string;
  if (generationPrompt) {
    prompt = generationPrompt;
    if (userNote) prompt += `\n\nDirector note: ${userNote}`;
  } else {
    prompt = buildEnvironmentPrompt(environment, { styleIdx, userRefIdx });
    if (userNote) prompt += `\n\nDirector note: ${userNote}`;
  }

  parts.push({ text: prompt });

  const singleCall = async (modelName: string): Promise<string | null> => {
    try {
      const response = await ai.models.generateContent({
        model: modelName,
        contents: [{ role: 'user', parts }],
        config: {
          responseModalities: ['IMAGE'],
          // @ts-ignore
          imageConfig: { aspectRatio }
        }
      });
      const paths = await extractImages(response);
      return paths[0] || null;
    } catch (err) {
      console.error(`[imagen] Environment variant failed (${modelName}):`, err);
      return null;
    }
  };

  let activeModel = model;
  let results = await Promise.all(Array.from({ length: N }, () => singleCall(activeModel)));
  let paths = results.filter((p): p is string => p !== null);
  if (paths.length === 0) {
    const fallback = DEFAULT_IMAGE_MODELS.find((candidate) => candidate !== activeModel);
    if (fallback) {
      console.warn(`[imagen] Environment looks (${activeModel}) returned 0/${N}; retrying with ${fallback}`);
      activeModel = fallback;
      results = await Promise.all(Array.from({ length: N }, () => singleCall(activeModel)));
      paths = results.filter((p): p is string => p !== null);
    }
  }
  console.log(`[imagen] Environment looks (${activeModel}): got ${paths.length}/${N} images via parallel calls`);
  if (paths.length === 0) {
    throw new Error(`Image provider returned zero environment look images after ${N} attempts.`);
  }
  return paths;
};

// ─── Shot Start Frame Generation (gemini-3-pro-image-preview) ───────

/**
 * Generate a shot's start frame with full reference chain.
 *
 * Uses a numbered reference index approach — each image is labeled with its role,
 * explicit usage instructions tell the model what to extract from each, and a
 * priority order resolves conflicts between references.
 */
export const generateShotStartFrame = async (opts: {
  visualPrompt: string;
  styleImagePath?: string;
  characterRefs: { name: string; imagePath: string }[];
  environmentRef?: { name: string; imagePath: string };
  prevShotEndFramePath?: string;
  continuityDescription?: string;
  userFeedback?: string;
  failedImagePath?: string;
  aspectRatio?: string;
  additionalRefs?: { imagePath: string }[];
}): Promise<string> => {
  const parts: ContentPart[] = [];

  // ── Build reference index ──
  // Number each image so the model can unambiguously refer to them.
  let imageIdx = 0;

  // Character references (highest priority — identity must be preserved)
  for (const ref of opts.characterRefs) {
    imageIdx++;
    parts.push({ text: `Image ${imageIdx} = Character: ${ref.name}` });
    parts.push(await imagePartFromPath(ref.imagePath));
  }

  // Style reference
  if (opts.styleImagePath) {
    imageIdx++;
    parts.push({ text: `Image ${imageIdx} = Style reference` });
    parts.push(await imagePartFromPath(opts.styleImagePath));
  }

  // Environment reference
  if (opts.environmentRef) {
    imageIdx++;
    parts.push({ text: `Image ${imageIdx} = Environment reference: ${opts.environmentRef.name}` });
    parts.push(await imagePartFromPath(opts.environmentRef.imagePath));
  }

  // Additional user-uploaded references for this shot
  if (opts.additionalRefs?.length) {
    for (const ref of opts.additionalRefs) {
      imageIdx++;
      parts.push({ text: `Image ${imageIdx} = Director reference (match composition, mood, or elements from this image)` });
      parts.push(await imagePartFromPath(ref.imagePath));
    }
  }

  // Continuity reference (previous shot's end frame)
  if (opts.prevShotEndFramePath) {
    imageIdx++;
    parts.push({ text: `Image ${imageIdx} = Last-scene continuity reference` });
    parts.push(await imagePartFromPath(opts.prevShotEndFramePath));
  }

  // Failed previous attempt — show the model what went wrong so it avoids
  // the same issues. Only included when user gave feedback + we have the old image.
  if (opts.failedImagePath && opts.userFeedback) {
    imageIdx++;
    parts.push({ text: `Image ${imageIdx} = PREVIOUS ATTEMPT (rejected). Problems: ${opts.userFeedback}. Do NOT repeat these issues.` });
    parts.push(await imagePartFromPath(opts.failedImagePath));
  }

  // ── Scene + instructions ──
  let prompt = `Scene: ${opts.visualPrompt}

Preserve character identity from character references (face, costume, ornaments must match). Match environment from environment reference. ${opts.prevShotEndFramePath ? 'Continue visual flow from previous shot. ' : ''}Match the visual style EXACTLY from the style reference image — same lighting, color palette, texture, and rendering approach. The style image is the ground truth.`;

  if (opts.continuityDescription) {
    prompt += `\n\nPrevious shot ended with: ${opts.continuityDescription}
This shot should begin from that exact continuity state — matching pose, camera position, lighting, and mid-action beats — then transition into the scene described above.`;
  }

  if (opts.userFeedback) {
    prompt += `\n\nDirector note: ${opts.userFeedback}`;
  }

  // Medium-neutral close. The style image carries the medium signal — adding
  // "cinematic frame" / "film still" in text was pulling stylized projects
  // back toward realism. See docs/cinematic-leak-audit-2026-05-12.md.
  prompt += `\n\nSingle frame. No text, no watermark.\nAvoid: overly AI/CGI look, excessive intricate detail, generic fantasy.`;

  parts.push({ text: prompt });

  return generateImageWithRefs(parts, opts.aspectRatio || '16:9');
};

// ─── Shot End Frame Generation (gemini-3-pro-image-preview) ──────────

/**
 * Generate a shot's end frame from its start frame + motion prompt.
 * The start frame IS the continuity reference — the end frame shows
 * where the camera/action ends up after the described motion.
 */
export const generateShotEndFrame = async (opts: {
  startFramePath?: string;
  visualPrompt: string;
  motionPrompt: string;
  styleImagePath?: string;
  characterRefs?: { name: string; imagePath: string }[];
  environmentRef?: { name: string; imagePath: string };
  additionalRefs?: { imagePath: string }[];
  userFeedback?: string;
  failedImagePath?: string;
}): Promise<string> => {
  const parts: ContentPart[] = [];
  let imageIdx = 0;

  if (opts.startFramePath) {
    imageIdx++;
    parts.push({ text: `Image ${imageIdx} = Start frame of this shot` });
    parts.push(await imagePartFromPath(opts.startFramePath));
  }

  // Character refs (when artist explicitly adds them)
  if (opts.characterRefs?.length) {
    for (const ref of opts.characterRefs) {
      imageIdx++;
      parts.push({ text: `Image ${imageIdx} = Character: ${ref.name}` });
      parts.push(await imagePartFromPath(ref.imagePath));
    }
  }

  if (opts.styleImagePath) {
    imageIdx++;
    parts.push({ text: `Image ${imageIdx} = Style reference` });
    parts.push(await imagePartFromPath(opts.styleImagePath));
  }

  if (opts.environmentRef) {
    imageIdx++;
    parts.push({ text: `Image ${imageIdx} = Environment reference: ${opts.environmentRef.name}` });
    parts.push(await imagePartFromPath(opts.environmentRef.imagePath));
  }

  if (opts.additionalRefs?.length) {
    for (const ref of opts.additionalRefs) {
      imageIdx++;
      parts.push({ text: `Image ${imageIdx} = Director reference` });
      parts.push(await imagePartFromPath(ref.imagePath));
    }
  }

  if (opts.failedImagePath && opts.userFeedback) {
    imageIdx++;
    parts.push({ text: `Image ${imageIdx} = PREVIOUS END FRAME ATTEMPT (rejected). Problems: ${opts.userFeedback}. Do NOT repeat these issues.` });
    parts.push(await imagePartFromPath(opts.failedImagePath));
  }

  let prompt = `Scene: ${opts.visualPrompt}

Motion: ${opts.motionPrompt}

Image 1 is the start frame of this shot. Generate the ending frame — what the camera sees after the motion described above. Same characters, same costumes, same environment, moments later. Match the visual style exactly from the start frame.`;

  if (opts.userFeedback) {
    prompt += `\n\nDirector note: ${opts.userFeedback}`;
  }

  prompt += `\n\nNo text, no watermark.\nAvoid: overly AI/CGI look, excessive intricate detail, generic fantasy.`;

  parts.push({ text: prompt });

  return generateImageWithRefs(parts);
};

// ─── Shot Frame Pair Generation (single call, start + end) ───────────

/**
 * Generate both start and end frame in a single API call.
 * The model creates the start frame first, then has perfect memory of it
 * when generating the end frame — much better consistency than two calls.
 *
 * Falls back to separate calls if the model only returns one image.
 */
export const generateShotFramePair = async (opts: {
  visualPrompt: string;
  motionPrompt: string;
  styleImagePath?: string;
  characterRefs: { name: string; imagePath: string }[];
  environmentRef?: { name: string; imagePath: string };
  prevShotEndFramePath?: string;
  userFeedback?: string;
}): Promise<{ startFramePath: string; endFramePath: string }> => {
  const ai = getAI();
  const parts: ContentPart[] = [];

  // ── Build reference index (same as start frame) ──
  let imageIdx = 0;

  for (const ref of opts.characterRefs) {
    imageIdx++;
    parts.push({ text: `Image ${imageIdx} = Character: ${ref.name}` });
    parts.push(await imagePartFromPath(ref.imagePath));
  }

  if (opts.styleImagePath) {
    imageIdx++;
    parts.push({ text: `Image ${imageIdx} = Style reference` });
    parts.push(await imagePartFromPath(opts.styleImagePath));
  }

  if (opts.environmentRef) {
    imageIdx++;
    parts.push({ text: `Image ${imageIdx} = Environment: ${opts.environmentRef.name}` });
    parts.push(await imagePartFromPath(opts.environmentRef.imagePath));
  }

  if (opts.prevShotEndFramePath) {
    imageIdx++;
    parts.push({ text: `Image ${imageIdx} = Previous shot end frame — match continuity` });
    parts.push(await imagePartFromPath(opts.prevShotEndFramePath));
  }

  // ── Prompt for both frames ──
  let prompt = `Scene: ${opts.visualPrompt}

Motion: ${opts.motionPrompt}

Generate TWO images for this shot:

IMAGE 1 — START FRAME: The opening moment of this shot. Preserve character identity from character references. Match environment from environment reference. ${opts.prevShotEndFramePath ? 'Continue visual flow from previous shot. ' : ''}Match the visual style EXACTLY from the style reference image.

IMAGE 2 — END FRAME: The closing moment of this shot, after the motion described above. Same characters, same costumes, same environment as the start frame, moments later.`;

  if (opts.userFeedback) {
    prompt += `\n\nDirector note: ${opts.userFeedback}`;
  }

  prompt += `\n\nTwo frames. No text, no watermark.\nAvoid: overly AI/CGI look, excessive intricate detail, generic fantasy.`;

  parts.push({ text: prompt });

  // ── Call model ──
  const response = await ai.models.generateContent({
    model: 'gemini-3-pro-image-preview',
    contents: [{ role: 'user', parts }],
    config: {
      responseModalities: ['IMAGE'],
      // @ts-ignore
      imageConfig: { aspectRatio: '16:9' }
    }
  });

  const images = await extractImages(response);

  if (images.length >= 2) {
    console.log(`[shot-frame-pair] Got ${images.length} images in single call`);
    return { startFramePath: images[0], endFramePath: images[1] };
  }

  if (images.length === 1) {
    // Only got start frame — fall back to separate end frame call
    console.warn(`[shot-frame-pair] Only got 1 image, falling back to separate end frame call`);
    const endFramePath = await generateShotEndFrame({
      startFramePath: images[0],
      visualPrompt: opts.visualPrompt,
      motionPrompt: opts.motionPrompt,
      styleImagePath: opts.styleImagePath,
    });
    return { startFramePath: images[0], endFramePath };
  }

  throw new Error('No images generated in frame pair call');
};
