import fs from 'fs';
import path from 'path';
import OpenAI from 'openai';
import type { ImagesResponse } from 'openai/resources/images';
import { downloadToTmp, mimeFromExt, saveBase64 } from '../storage.js';
import { getRuntimePreset, type PipelinePreset } from '../presets.js';
import { buildCharacterPrompt, buildEnvironmentPrompt, buildStylePrompt } from './imagen.js';
import { getImageModel } from '../../constants/imageModels.js';
import { requireProviderApiKey } from './byok/providerKeys.js';

type ContentPart = { text: string } | { inlineData: { mimeType: string; data: string } };

type RefImage = {
  label: string;
  imagePath?: string;
  inlineData?: { mimeType: string; data: string };
};

export type OpenAIRefImage = RefImage;

const OPENAI_MODEL = getImageModel('gpt-image-2').runtimeModel;
const OPENAI_RESPONSES_IMAGE_MODEL = process.env.OPENAI_RESPONSES_IMAGE_MODEL || 'gpt-5.5';
const MAX_OPENAI_INPUT_IMAGES = 10;
const SUPPORTS_INPUT_FIDELITY = new Set(['gpt-image-1', 'gpt-image-1.5', 'chatgpt-image-latest']);

const getClient = async () => new OpenAI({ apiKey: await requireProviderApiKey('openai') });

const detectImageExt = (base64: string): string => {
  if (base64.startsWith('/9j/') || base64.startsWith('/9j+')) return 'jpg';
  if (base64.startsWith('UklGR')) return 'webp';
  return 'png';
};

const sizeForAspectRatio = (aspectRatio = '16:9'): string => {
  switch (aspectRatio) {
    case '9:16':
      return '1024x1536';
    case '1:1':
      return '1024x1024';
    default:
      return '1536x1024';
  }
};

const buildReferenceIndex = (refs: RefImage[]): string => {
  if (refs.length === 0) return '';
  return `Reference images provided in order:\n${refs.map((ref, idx) => `${idx + 1}. ${ref.label}`).join('\n')}\n\n`;
};

const toUploadable = async (ref: RefImage, idx: number): Promise<File> => {
  if (ref.inlineData) {
    const ext = ref.inlineData.mimeType.includes('jpeg')
      ? 'jpg'
      : ref.inlineData.mimeType.includes('webp')
        ? 'webp'
        : 'png';
    return new File([Buffer.from(ref.inlineData.data, 'base64')], `inline-${idx}.${ext}`, { type: ref.inlineData.mimeType });
  }

  if (!ref.imagePath) throw new Error(`Missing imagePath for ref ${idx + 1}`);

  const tmpPath = await downloadToTmp(ref.imagePath);
  const buffer = fs.readFileSync(tmpPath);
  const ext = path.extname(ref.imagePath).slice(1) || 'png';
  return new File([buffer], `ref-${idx}.${ext}`, { type: mimeFromExt(ref.imagePath) });
};

const uploadVisionFile = async (client: OpenAI, ref: RefImage, idx: number): Promise<string> => {
  const file = await toUploadable(ref, idx);
  const result = await client.files.create({
    file,
    purpose: 'vision' as any,
  });
  return result.id;
};

const saveGeneratedImages = async (response: ImagesResponse): Promise<string[]> => {
  const images = response.data || [];
  const paths: string[] = [];
  for (const image of images) {
    if (!image.b64_json) continue;
    paths.push(await saveBase64(image.b64_json, 'images', detectImageExt(image.b64_json)));
  }
  if (paths.length === 0) throw new Error('No image generated by OpenAI');
  return paths;
};

const generateFromPrompt = async (
  prompt: string,
  aspectRatio = '16:9',
  refs: RefImage[] = [],
  count = 1
): Promise<string[]> => {
  const client = await getClient();
  const size = sizeForAspectRatio(aspectRatio) as any;
  const cappedRefs = refs.slice(0, MAX_OPENAI_INPUT_IMAGES);

  if (cappedRefs.length > 0) {
    const files = await Promise.all(cappedRefs.map((ref, idx) => toUploadable(ref, idx)));
    const editRequest: any = {
      model: OPENAI_MODEL,
      image: files,
      prompt: `${buildReferenceIndex(cappedRefs)}${prompt}`,
      n: count,
      size,
      quality: 'medium',
      output_format: 'png',
    };
    if (SUPPORTS_INPUT_FIDELITY.has(OPENAI_MODEL)) editRequest.input_fidelity = 'high';
    const response = await client.images.edit(editRequest);
    return saveGeneratedImages(response);
  }

  const response = await client.images.generate({
    model: OPENAI_MODEL,
    prompt,
    n: count,
    size,
    quality: 'medium',
    output_format: 'png',
  });
  return saveGeneratedImages(response);
};

export const generateOpenAIImageFromPrompt = async (
  prompt: string,
  opts?: {
    aspectRatio?: string;
    refs?: OpenAIRefImage[];
    count?: number;
  }
): Promise<string[]> => {
  return generateFromPrompt(prompt, opts?.aspectRatio || '16:9', opts?.refs || [], opts?.count || 1);
};

export const generateOpenAIImageWithResponses = async (
  prompt: string,
  opts?: {
    aspectRatio?: string;
    size?: string;
    refs?: OpenAIRefImage[];
    previousResponseId?: string;
    action?: 'generate' | 'edit' | 'auto';
    quality?: 'low' | 'medium' | 'high' | 'auto';
  }
): Promise<{
  imagePaths: string[];
  responseId: string;
  imageGenerationCallIds: string[];
  imageGenerationRevisedPrompts: string[];
  outputText: string;
  reasoningModel: string;
  imageModel: string;
}> => {
  const client = await getClient();
  const cappedRefs = (opts?.refs || []).slice(0, MAX_OPENAI_INPUT_IMAGES);
  const fileIds = await Promise.all(cappedRefs.map((ref, idx) => uploadVisionFile(client, ref, idx)));
  const size = opts?.size || sizeForAspectRatio(opts?.aspectRatio || '16:9');

  const content: any[] = [
    { type: 'input_text', text: `${buildReferenceIndex(cappedRefs)}${prompt}` },
    ...fileIds.map((fileId) => ({ type: 'input_image', file_id: fileId, detail: 'high' })),
  ];

  const imageTool: any = {
    type: 'image_generation',
    model: OPENAI_MODEL,
    action: opts?.action || (opts?.previousResponseId ? 'edit' : 'generate'),
    output_format: 'png',
    quality: opts?.quality || 'medium',
    size,
  };
  if (SUPPORTS_INPUT_FIDELITY.has(OPENAI_MODEL)) imageTool.input_fidelity = 'high';

  const response = await (client.responses.create as any)({
    model: OPENAI_RESPONSES_IMAGE_MODEL,
    previous_response_id: opts?.previousResponseId,
    input: [{ role: 'user', content }],
    tools: [imageTool],
  });

  const imageCalls = (response.output || []).filter((item: any) => item.type === 'image_generation_call');
  const outputText = (response.output || [])
    .filter((item: any) => item.type === 'message')
    .flatMap((item: any) => item.content || [])
    .filter((content: any) => content.type === 'output_text' && content.text)
    .map((content: any) => content.text)
    .join('\n\n')
    .trim();
  const imagePaths: string[] = [];
  for (const call of imageCalls) {
    if (!call.result) continue;
    imagePaths.push(await saveBase64(call.result, 'images', detectImageExt(call.result)));
  }
  if (imagePaths.length === 0) throw new Error('No image generated by OpenAI Responses image tool');

  return {
    imagePaths,
    responseId: response.id,
    imageGenerationCallIds: imageCalls.map((call: any) => call.id).filter(Boolean),
    imageGenerationRevisedPrompts: imageCalls.map((call: any) => call.revised_prompt).filter(Boolean),
    outputText,
    reasoningModel: OPENAI_RESPONSES_IMAGE_MODEL,
    imageModel: OPENAI_MODEL,
  };
};

export const generateImageWithRefs = async (
  parts: ContentPart[],
  aspectRatio = '16:9'
): Promise<string> => {
  const texts: string[] = [];
  const refs: RefImage[] = [];

  let pendingLabel: string | null = null;
  for (const part of parts) {
    if ('text' in part) {
      texts.push(part.text);
      pendingLabel = part.text.startsWith('Image ') ? part.text.replace(/^Image \d+ = /, '') : null;
    } else {
      refs.push({
        label: pendingLabel || `Reference ${refs.length + 1}`,
        inlineData: part.inlineData,
      });
      pendingLabel = null;
    }
  }

  const [imagePath] = await generateFromPrompt(texts.join('\n\n'), aspectRatio, refs, 1);
  return imagePath;
};

export const generateStyleOptions = async (
  subject: string,
  styleNotes?: string,
  // eslint-disable-next-line @typescript-eslint/no-unused-vars -- signature parity with imagen.ts
  _projectId?: string,
  preset: PipelinePreset = getRuntimePreset(),
): Promise<{ style: string; assetPath: string }[]> => {
  const directions = styleNotes
    ? [
        `${styleNotes}`,
        `${styleNotes}, with dramatic chiaroscuro shadows and Renaissance-inspired composition`,
        `${styleNotes}, reimagined with clean high-key lighting and luminous color separation`,
        `${styleNotes}, as vintage 16mm film with warm analog grain and nostalgic color grading`,
      ]
    : [
        // Medium-neutral defaults — see docs/cinematic-leak-audit-2026-05-12.md.
        `Reference frame for ${subject}, natural light, balanced composition`,
        `${subject} with dramatic chiaroscuro shadows and a single warm light source, deep grounded mood`,
        `${subject} with high-key luminous color, soft bloom, clear atmospheric separation`,
        `${subject} with warm earthy color and tactile material texture`,
      ];

  const settled = await Promise.allSettled(
    directions.map(async (direction) => {
      const prompt = `Create one reusable visual style reference frame for ${preset.style.subjectPrompt(subject)}. ${direction}. Focus on lighting, atmosphere, medium, and visual treatment. ${preset.looks.qualityRules} No text, no watermark.`;
      const [assetPath] = await generateFromPrompt(prompt, '16:9', [], 1);
      return { style: direction, assetPath };
    })
  );

  return settled
    .filter((result): result is PromiseFulfilledResult<{ style: string; assetPath: string }> => result.status === 'fulfilled')
    .map((result) => result.value);
};

export const generateSingleStyleImage = async (
  styleDescription: string,
  subject: string,
  generationPrompt?: string,
  preset?: PipelinePreset,
): Promise<string> => {
  const prompt = generationPrompt || buildStylePrompt(styleDescription, subject, preset);
  const [assetPath] = await generateFromPrompt(prompt, '16:9', [], 1);
  return assetPath;
};

export const generateCharacterLooks = async (
  character: { name: string; description: string },
  styleImagePath?: string,
  userFeedback?: string,
  aspectRatio: string = '16:9',
  userRefImagePath?: string,
  generationPrompt?: string,
  // eslint-disable-next-line @typescript-eslint/no-unused-vars -- accepted for
  // signature parity with imagen.ts; OpenAI's image service has a single
  // model (gpt-image-2) so the registry's runtimeModel is informational here.
  _model?: string,
  preset?: PipelinePreset,
): Promise<string[]> => {
  const styleIdx = styleImagePath ? 1 : undefined;
  const userRefIdx = userRefImagePath ? (styleImagePath ? 2 : 1) : undefined;

  let prompt = generationPrompt || buildCharacterPrompt(character, { styleIdx, userRefIdx, preset });
  if (userFeedback) prompt += `\n\nDirector note: ${userFeedback}`;
  if (styleImagePath) {
    prompt += `\n\nImportant: Image 1 is a style reference only. Do not use Image 1 as the background, crop, pose, layout, subject, or composition. Create a new isolated character reference for ${character.name}.`;
  }

  const refs: RefImage[] = [];
  if (styleImagePath) refs.push({ label: 'Style reference', imagePath: styleImagePath });
  if (userRefImagePath) refs.push({ label: 'User-supplied character reference', imagePath: userRefImagePath });

  return generateFromPrompt(prompt, aspectRatio, refs, 3);
};

export const generateEnvironmentLooks = async (
  environment: { name: string; description: string },
  styleImagePath?: string,
  aspectRatio: string = '16:9',
  userRefImagePath?: string,
  userNote?: string,
  generationPrompt?: string,
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  _model?: string,
  preset?: PipelinePreset,
): Promise<string[]> => {
  const styleIdx = styleImagePath ? 1 : undefined;
  const userRefIdx = userRefImagePath ? (styleImagePath ? 2 : 1) : undefined;

  let prompt = generationPrompt || buildEnvironmentPrompt(environment, { styleIdx, userRefIdx, preset });
  if (userNote) prompt += `\n\nDirector note: ${userNote}`;
  if (styleImagePath) {
    prompt += `\n\nImportant: Image 1 is a style reference only. Do not use Image 1 as the crop, layout, subject, or composition. Create a new clean environment reference for ${environment.name}.`;
  }

  const refs: RefImage[] = [];
  if (styleImagePath) refs.push({ label: 'Style reference', imagePath: styleImagePath });
  if (userRefImagePath) refs.push({ label: 'User-supplied environment reference', imagePath: userRefImagePath });

  return generateFromPrompt(prompt, aspectRatio, refs, 3);
};

export const generateShotStartFrame = async (opts: {
  visualPrompt: string;
  styleImagePath?: string;
  characterRefs: { name: string; imagePath: string }[];
  environmentRef?: { name: string; imagePath: string };
  prevShotEndFramePath?: string;
  continuityDescription?: string;
  userFeedback?: string;
  failedImagePath?: string;
  aspectRatio?: string;
  additionalRefs?: { imagePath: string }[];
}): Promise<string> => {
  const refs: RefImage[] = [];

  for (const ref of opts.characterRefs) refs.push({ label: `Character: ${ref.name}`, imagePath: ref.imagePath });
  if (opts.styleImagePath) refs.push({ label: 'Style reference', imagePath: opts.styleImagePath });
  if (opts.environmentRef) refs.push({ label: `Environment reference: ${opts.environmentRef.name}`, imagePath: opts.environmentRef.imagePath });
  for (const ref of opts.additionalRefs || []) refs.push({ label: 'Director reference', imagePath: ref.imagePath });
  if (opts.prevShotEndFramePath) refs.push({ label: 'Last-scene continuity reference', imagePath: opts.prevShotEndFramePath });
  if (opts.failedImagePath && opts.userFeedback) {
    refs.push({ label: `PREVIOUS ATTEMPT (rejected). Problems: ${opts.userFeedback}. Do NOT repeat these issues.`, imagePath: opts.failedImagePath });
  }

  let prompt = `Scene: ${opts.visualPrompt}

Preserve character identity from the character references. Match the environment from the environment reference. ${opts.prevShotEndFramePath ? 'Continue visual flow from the continuity reference. ' : ''}Match the visual style exactly from the style reference image.`;

  if (opts.continuityDescription) {
    prompt += `\n\nPrevious shot ended with: ${opts.continuityDescription}
This shot should begin from that exact continuity state — matching pose, camera position, lighting, and mid-action beats — then transition into the scene described above.`;
  }

  if (opts.userFeedback) prompt += `\n\nDirector note: ${opts.userFeedback}`;
  // Medium-neutral — style image is the ground truth. See
  // docs/cinematic-leak-audit-2026-05-12.md.
  prompt += `\n\nSingle frame. No text, no watermark.\nAvoid: overly AI/CGI look, excessive intricate detail, generic fantasy.`;

  const [assetPath] = await generateFromPrompt(prompt, opts.aspectRatio || '16:9', refs, 1);
  return assetPath;
};

export const generateShotEndFrame = async (opts: {
  startFramePath?: string;
  visualPrompt: string;
  motionPrompt: string;
  styleImagePath?: string;
  characterRefs?: { name: string; imagePath: string }[];
  environmentRef?: { name: string; imagePath: string };
  additionalRefs?: { imagePath: string }[];
  userFeedback?: string;
  failedImagePath?: string;
}): Promise<string> => {
  const refs: RefImage[] = [];

  if (opts.startFramePath) refs.push({ label: 'Start frame of this shot', imagePath: opts.startFramePath });
  for (const ref of opts.characterRefs || []) refs.push({ label: `Character: ${ref.name}`, imagePath: ref.imagePath });
  if (opts.styleImagePath) refs.push({ label: 'Style reference', imagePath: opts.styleImagePath });
  if (opts.environmentRef) refs.push({ label: `Environment reference: ${opts.environmentRef.name}`, imagePath: opts.environmentRef.imagePath });
  for (const ref of opts.additionalRefs || []) refs.push({ label: 'Director reference', imagePath: ref.imagePath });
  if (opts.failedImagePath && opts.userFeedback) {
    refs.push({ label: `PREVIOUS END FRAME ATTEMPT (rejected). Problems: ${opts.userFeedback}. Do NOT repeat these issues.`, imagePath: opts.failedImagePath });
  }

  let prompt = `Scene: ${opts.visualPrompt}

Motion: ${opts.motionPrompt}

The first reference image is the start frame of this shot. Generate the ending frame — what the camera sees after the motion described above. Same characters, same costumes, same environment, moments later. Match the visual style exactly from the start frame.`;

  if (opts.userFeedback) prompt += `\n\nDirector note: ${opts.userFeedback}`;
  prompt += `\n\nNo text, no watermark.\nAvoid: overly AI/CGI look, excessive intricate detail, generic fantasy.`;

  const [assetPath] = await generateFromPrompt(prompt, '16:9', refs, 1);
  return assetPath;
};
