// 1:1 from reference: src/features/editor/data/transitions.ts
export const TRANSITIONS = [
  {
    id: '1',
    kind: 'none',
    duration: 0,
    preview: 'https://ik.imagekit.io/wombo/transitions-v2/transition-none.png',
    type: 'transition' as const,
  },
  {
    id: '2',
    kind: 'fade',
    duration: 0.5,
    preview: 'https://ik.imagekit.io/wombo/transitions-v2/fade.webp',
    type: 'transition' as const,
  },
  {
    id: '3',
    kind: 'slide',
    name: 'slide up',
    duration: 0.5,
    preview: 'https://ik.imagekit.io/wombo/transitions-v2/slide-up.webp',
    type: 'transition' as const,
    direction: 'from-bottom' as const,
  },
  {
    id: '4',
    kind: 'slide',
    name: 'slide down',
    duration: 0.5,
    preview: 'https://ik.imagekit.io/wombo/transitions-v2/slide-down.webp',
    type: 'transition' as const,
    direction: 'from-top' as const,
  },
  {
    id: '5',
    kind: 'slide',
    name: 'slide left',
    duration: 0.5,
    preview: 'https://ik.imagekit.io/wombo/transitions-v2/slide-left.webp',
    type: 'transition' as const,
    direction: 'from-right' as const,
  },
  {
    id: '6',
    kind: 'slide',
    name: 'slide right',
    duration: 0.5,
    preview: 'https://ik.imagekit.io/wombo/transitions-v2/slide-right.webp',
    type: 'transition' as const,
    direction: 'from-left' as const,
  },
  {
    id: '7',
    kind: 'wipe',
    name: 'wipe up',
    duration: 0.5,
    preview: 'https://ik.imagekit.io/wombo/transitions-v2/wipe-up.webp',
    type: 'transition' as const,
    direction: 'from-bottom' as const,
  },
  {
    id: '8',
    kind: 'wipe',
    name: 'wipe down',
    duration: 0.5,
    preview: 'https://ik.imagekit.io/wombo/transitions-v2/wipe-down.webp',
    type: 'transition' as const,
    direction: 'from-top' as const,
  },
  {
    id: '9',
    kind: 'wipe',
    name: 'wipe left',
    duration: 0.5,
    preview: 'https://ik.imagekit.io/wombo/transitions-v2/wipe-left.webp',
    type: 'transition' as const,
    direction: 'from-right' as const,
  },
  {
    id: '10',
    kind: 'wipe',
    name: 'wipe right',
    duration: 0.5,
    preview: 'https://ik.imagekit.io/wombo/transitions-v2/wipe-right.webp',
    type: 'transition' as const,
    direction: 'from-left' as const,
  },
  {
    id: '11',
    kind: 'flip',
    duration: 0.5,
    preview: 'https://ik.imagekit.io/wombo/transitions-v2/flip.webp',
    type: 'transition' as const,
  },
  {
    id: '12',
    kind: 'clockWipe',
    duration: 0.5,
    preview: 'https://ik.imagekit.io/wombo/transitions-v2/clock-wipe.webp',
    type: 'transition' as const,
  },
  {
    id: '13',
    kind: 'star',
    duration: 0.5,
    preview: 'https://ik.imagekit.io/wombo/transitions-v2/star.webp',
    type: 'transition' as const,
  },
  {
    id: '14',
    kind: 'circle',
    duration: 0.5,
    preview: 'https://ik.imagekit.io/wombo/transitions-v2/circle.webp',
    type: 'transition' as const,
  },
  {
    id: '15',
    kind: 'rectangle',
    duration: 0.5,
    preview: 'https://ik.imagekit.io/wombo/transitions-v2/rectangle.webp',
    type: 'transition' as const,
  },
];
