## Table `batch_jobs`

Track batch video generation jobs

### Columns

| Name | Type | Constraints |
|------|------|-------------|
| `id` | `uuid` | Primary |
| `song_id` | `uuid` |  |
| `clip_id` | `uuid` |  Nullable |
| `job_type` | `text` |  Nullable |
| `status` | `text` |  Nullable |
| `progress` | `jsonb` |  Nullable |
| `logs` | `text` |  Nullable |
| `started_at` | `timestamptz` |  Nullable |
| `completed_at` | `timestamptz` |  Nullable |
| `created_at` | `timestamptz` |  Nullable |

## Table `bot_conversations`

Telegram bot conversation history per chat

### Columns

| Name | Type | Constraints |
|------|------|-------------|
| `chat_id` | `int8` | Primary |
| `messages` | `jsonb` |  Nullable |
| `context` | `jsonb` |  Nullable |
| `last_active_at` | `timestamptz` |  Nullable |

## Table `clips`

Deity-based reusable clips generated by Pixel Flows (not per-song)

### Columns

| Name | Type | Constraints |
|------|------|-------------|
| `id` | `uuid` | Primary |
| `deity` | `text` |  |
| `clip_name` | `text` |  |
| `seed_prompt` | `text` |  Nullable |
| `seed_image_url` | `text` |  |
| `clip_url` | `text` |  |
| `storage_provider` | `text` |  Nullable |
| `is_default` | `bool` |  Nullable |
| `usage_count` | `int4` |  Nullable |
| `created_at` | `timestamptz` |  Nullable |
| `drive_file_id` | `text` |  Nullable |

## Table `files`

Unified table for all file assets (audio, SRTs, references)

### Columns

| Name | Type | Constraints |
|------|------|-------------|
| `id` | `uuid` | Primary |
| `song_id` | `uuid` |  |
| `file_type` | `text` |  |
| `language` | `text` |  Nullable |
| `storage_provider` | `text` |  Nullable |
| `storage_url` | `text` |  |
| `file_size_mb` | `numeric` |  Nullable |
| `metadata` | `jsonb` |  Nullable |
| `created_at` | `timestamptz` |  Nullable |

## Table `lahari_ai_calls`

### Columns

| Name | Type | Constraints |
|------|------|-------------|
| `id` | `text` | Primary |
| `project_id` | `text` |  |
| `stage` | `text` |  |
| `model` | `text` |  |
| `prompt` | `text` |  |
| `reference_inputs` | `text` |  Nullable |
| `context_chain` | `text` |  Nullable |
| `response_summary` | `text` |  Nullable |
| `output_asset_ids` | `text` |  Nullable |
| `duration_ms` | `int4` |  Nullable |
| `cost_estimate` | `float4` |  Nullable |
| `error` | `text` |  Nullable |
| `created_at` | `timestamptz` |  Nullable |

## Table `lahari_assets`

### Columns

| Name | Type | Constraints |
|------|------|-------------|
| `id` | `text` | Primary |
| `project_id` | `text` |  |
| `shot_id` | `text` |  Nullable |
| `category` | `text` |  |
| `file_path` | `text` |  |
| `prompt` | `text` |  Nullable |
| `metadata` | `text` |  Nullable |
| `created_at` | `timestamptz` |  Nullable |

## Table `lahari_cast_members`

### Columns

| Name | Type | Constraints |
|------|------|-------------|
| `id` | `text` | Primary |
| `project_id` | `text` |  |
| `name` | `text` |  |
| `description` | `text` |  Nullable |
| `reference_asset_id` | `text` |  Nullable |
| `sort_order` | `int4` |  Nullable |
| `generation_prompt` | `text` |  Nullable |
| `prompts_stale` | `bool` |  Nullable |

## Table `lahari_chat_messages`

### Columns

| Name | Type | Constraints |
|------|------|-------------|
| `id` | `int4` | Primary |
| `project_id` | `text` |  |
| `role` | `text` |  |
| `text` | `text` |  |
| `created_at` | `timestamptz` |  Nullable |

## Table `lahari_environments`

### Columns

| Name | Type | Constraints |
|------|------|-------------|
| `id` | `text` | Primary |
| `project_id` | `text` |  |
| `name` | `text` |  |
| `description` | `text` |  Nullable |
| `reference_asset_id` | `text` |  Nullable |
| `sort_order` | `int4` |  Nullable |
| `generation_prompt` | `text` |  Nullable |
| `prompts_stale` | `bool` |  Nullable |

## Table `lahari_projects`

### Columns

| Name | Type | Constraints |
|------|------|-------------|
| `id` | `text` | Primary |
| `title` | `text` |  Nullable |
| `status` | `text` |  Nullable |
| `audio_path` | `text` |  Nullable |
| `lyrics` | `text` |  Nullable |
| `musical_structure` | `text` |  Nullable |
| `concept_options` | `text` |  Nullable |
| `locked_concept` | `text` |  Nullable |
| `style_description` | `text` |  Nullable |
| `style_asset_id` | `text` |  Nullable |
| `color_palette` | `text` |  Nullable |
| `meaning` | `text` |  Nullable |
| `video_mode` | `text` |  Nullable |
| `target_duration` | `int4` |  Nullable |
| `cost_estimate` | `float4` |  Nullable |
| `style_exploration` | `text` |  Nullable |
| `last_script_prompt` | `text` |  Nullable |
| `last_concept_prompt` | `text` |  Nullable |
| `last_write_shots_prompt` | `text` |  Nullable |
| `aspect_ratio` | `text` |  Nullable |
| `video_resolution` | `text` |  Nullable |
| `video_model` | `text` |  Nullable |
| `parent_project_id` | `text` |  Nullable |
| `created_at` | `timestamptz` |  Nullable |
| `updated_at` | `timestamptz` |  Nullable |
| `style_generation_prompt` | `text` |  Nullable |
| `user_id` | `uuid` |  Nullable |
| `source_queue_id` | `text` |  Nullable |

## Table `lahari_renders`

### Columns

| Name | Type | Constraints |
|------|------|-------------|
| `id` | `text` | Primary |
| `project_id` | `text` |  |
| `status` | `text` |  |
| `video_url` | `text` |  Nullable |
| `storage_path` | `text` |  Nullable |
| `error` | `text` |  Nullable |
| `render_ms` | `int8` |  Nullable |
| `created_at` | `timestamptz` |  |
| `updated_at` | `timestamptz` |  |

## Table `lahari_scenes`

### Columns

| Name | Type | Constraints |
|------|------|-------------|
| `id` | `text` | Primary |
| `project_id` | `text` |  |
| `section_label` | `text` |  Nullable |
| `start_time` | `text` |  Nullable |
| `end_time` | `text` |  Nullable |
| `lyrics` | `text` |  Nullable |
| `narrative_description` | `text` |  Nullable |
| `sort_order` | `int4` |  Nullable |

## Table `lahari_shots`

### Columns

| Name | Type | Constraints |
|------|------|-------------|
| `id` | `text` | Primary |
| `scene_id` | `text` |  |
| `visual_prompt` | `text` |  Nullable |
| `motion_prompt` | `text` |  Nullable |
| `duration` | `float4` |  Nullable |
| `cast_ids` | `text` |  Nullable |
| `image_asset_id` | `text` |  Nullable |
| `video_asset_id` | `text` |  Nullable |
| `end_image_asset_id` | `text` |  Nullable |
| `extracted_last_frame_asset_id` | `text` |  Nullable |
| `image_status` | `text` |  Nullable |
| `video_status` | `text` |  Nullable |
| `end_image_status` | `text` |  Nullable |
| `critique` | `text` |  Nullable |
| `attempt_count` | `int4` |  Nullable |
| `use_next_as_end_frame` | `int4` |  Nullable |
| `sort_order` | `int4` |  Nullable |
| `locked` | `int4` |  Nullable |
| `user_feedback` | `text` |  Nullable |
| `environment_id` | `text` |  Nullable |
| `continuity_from` | `text` |  Nullable |
| `continuity_description` | `text` |  Nullable |
| `refined_from_prev_frame` | `int4` |  Nullable |
| `end_visual_prompt` | `text` |  Nullable |
| `end_user_feedback` | `text` |  Nullable |
| `prompts_stale` | `bool` |  Nullable |
| `last_error` | `text` |  Nullable |

## Table `music_video_queue`

### Columns

| Name | Type | Constraints |
|------|------|-------------|
| `id` | `uuid` | Primary |
| `song_id` | `uuid` |  |
| `priority` | `int4` |  Nullable |
| `status` | `text` |  Nullable |
| `lahari_project_id` | `text` |  Nullable |
| `video_url` | `text` |  Nullable |
| `notes` | `text` |  Nullable |
| `assigned_to` | `text` |  Nullable |
| `created_at` | `timestamptz` |  Nullable |
| `updated_at` | `timestamptz` |  Nullable |

## Table `projects`

### Columns

| Name | Type | Constraints |
|------|------|-------------|
| `id` | `text` | Primary |
| `name` | `text` |  |
| `total_duration_ms` | `int8` |  |
| `status` | `text` |  |
| `created_at` | `timestamptz` |  |
| `updated_at` | `timestamptz` |  |

## Table `render_jobs`

### Columns

| Name | Type | Constraints |
|------|------|-------------|
| `id` | `text` | Primary |
| `project_id` | `text` |  |
| `status` | `text` |  |
| `progress` | `jsonb` |  |
| `output_url` | `text` |  Nullable |
| `error` | `text` |  Nullable |
| `created_at` | `timestamptz` |  |
| `updated_at` | `timestamptz` |  |

## Table `shots`

### Columns

| Name | Type | Constraints |
|------|------|-------------|
| `id` | `text` | Primary |
| `project_id` | `text` |  |
| `pair_key` | `text` |  |
| `source_filename` | `text` |  |
| `audio_filename` | `text` |  |
| `shot_index` | `int4` |  |
| `start_time_ms` | `int8` |  |
| `end_time_ms` | `int8` |  |
| `duration_ms` | `int8` |  |
| `source_clip_url` | `text` |  |
| `source_clip_path` | `text` |  |
| `source_width` | `int4` |  |
| `source_height` | `int4` |  |
| `source_fps` | `float4` |  |
| `audio_segment_url` | `text` |  |
| `audio_segment_path` | `text` |  |
| `face_still_url` | `text` |  Nullable |
| `face_still_path` | `text` |  Nullable |
| `driver_clip_url` | `text` |  Nullable |
| `driver_clip_path` | `text` |  Nullable |
| `sync_output_url` | `text` |  Nullable |
| `sync_output_path` | `text` |  Nullable |
| `final_output_url` | `text` |  Nullable |
| `final_output_path` | `text` |  Nullable |
| `direct_status` | `text` |  |
| `driver_status` | `text` |  |
| `transfer_status` | `text` |  |
| `suitability` | `text` |  |
| `provider_mode` | `text` |  |
| `prompt` | `text` |  |
| `guidance_scale` | `float4` |  |
| `audio_guidance_scale` | `float4` |  |
| `runway_task_id` | `text` |  Nullable |
| `provider_job_id` | `text` |  Nullable |
| `driver_provider_job_id` | `text` |  Nullable |
| `is_final` | `bool` |  |
| `notes` | `text` |  Nullable |
| `updated_at` | `timestamptz` |  |

## Table `songs`

Main registry of 1500 devotional songs

### Columns

| Name | Type | Constraints |
|------|------|-------------|
| `id` | `uuid` | Primary |
| `song_number` | `int4` |  Unique |
| `song_name` | `text` |  |
| `deity` | `text` |  |
| `original_language` | `text` |  |
| `duration_seconds` | `int4` |  |
| `album` | `text` |  Nullable |
| `isrc` | `text` |  Unique |
| `has_reference_lyrics` | `bool` |  Nullable |
| `audio_uploaded` | `bool` |  Nullable |
| `srts_ready` | `bool` |  Nullable |
| `clips_available` | `bool` |  Nullable |
| `videos_complete` | `bool` |  Nullable |
| `youtube_uploaded` | `bool` |  Nullable |
| `created_at` | `timestamptz` |  Nullable |
| `updated_at` | `timestamptz` |  Nullable |
| `assigned_clip_id` | `uuid` |  Nullable |
| `drive_srt_url` | `text` |  Nullable |
| `drive_clip_url` | `text` |  Nullable |
| `drive_video_url` | `text` |  Nullable |
| `drive_audio_url` | `text` |  Nullable |
| `audio_storage_url` | `text` |  Nullable |
| `transcription_status` | `text` |  Nullable |
| `transcription_flags` | `jsonb` |  Nullable |
| `transcribed_at` | `timestamptz` |  Nullable |
| `reviewed_by` | `text` |  Nullable |
| `timestamp_synced` | `bool` |  Nullable |
| `cached_lyrics` | `text` |  Nullable |
| `cached_structure` | `text` |  Nullable |
| `cached_meaning` | `text` |  Nullable |

## Table `videos`

One record per language per song (5 videos per song)

### Columns

| Name | Type | Constraints |
|------|------|-------------|
| `id` | `uuid` | Primary |
| `song_id` | `uuid` |  |
| `clip_id` | `uuid` |  Nullable |
| `language` | `text` |  |
| `font_size` | `int4` |  Nullable |
| `render_status` | `text` |  Nullable |
| `render_attempts` | `int4` |  Nullable |
| `last_render_at` | `timestamptz` |  Nullable |
| `render_error` | `text` |  Nullable |
| `verified` | `bool` |  Nullable |
| `needs_rerender` | `bool` |  Nullable |
| `verification_notes` | `text` |  Nullable |
| `video_url` | `text` |  Nullable |
| `file_size_mb` | `numeric` |  Nullable |
| `created_at` | `timestamptz` |  Nullable |
| `updated_at` | `timestamptz` |  Nullable |

